version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8080:5000"
    secrets:
      - spell_secret_key
    volumes:
      - "/tmp/secrets.txt:/tmp/secrets.txt:ro"

secrets:
  spell_secret_key:
    file: /classes/csgy9163/Assignment3/secrets.txt
    
